target("IOManagerTest1")
    set_kind("binary")
    add_files("main1.cpp")
    add_deps("dfiber")
target_end()

target("IOManagerTest2")
    set_kind("binary")
    add_files("main2.cpp")
    add_deps("dfiber")
target_end()
